Removed double queue in text
esp-rs/espressif-trainings pull request #24
Opened 2022-03-01 14:53 UTC by Dajamante

Removed double creating queue, redid numerotation so it match the example code.

2022-03-01 15:33 UTC, Mirabellensaft requested changes

2022-03-01 15:33 UTC, Mirabellensaft commented on advanced/button-interrupt/exercise/src/main.rs
> +        // 3. write the global GPIO interrupt handler
```suggestion
        // 3. Install the global GPIO interrupt handler
```

2022-03-01 15:33 UTC, Mirabellensaft commented on book/src/04_4_interrupts.md
> +✅ Configure the button GPIO 9 with a c struct [`gpio_config_t`](https://esp-rs.github.io/esp-idf-sys/esp_idf_sys/struct.gpio_config_t.html)the following settings (1. in the exercise/src/main.rs):
Please leave the numbers as they corresponded to what I asked in the code. when the numbers are there, you don't need to reference to the numbers in ( )

2022-03-01 15:33 UTC, Mirabellensaft commented on book/src/04_4_interrupts.md
> +### Hints!
these are not hints, these are steps that need to be taken the way they are.

2022-03-01 15:33 UTC, Mirabellensaft commented on book/src/04_4_interrupts.md
> +- The other two constants you need to set to true have been imported by `esp_idf_sys`, so use those or just 1.
I have added more explanation for this in my PR so people can work more independent.

2022-03-01 15:33 UTC, Mirabellensaft commented on advanced/button-interrupt/exercise/src/main.rs
> -                1 => println!("button pressed!"),
I left the match intentionally there so the focus is on the c bindings and not on writing Rust. It would be good to revert the numbering.

2022-03-02 07:16 UTC, closed without merging

2022-03-02 07:17 UTC, Dajamante commented
The original state of text and code were better adapted to the training.